spring:
  application:
    name: kafka-xray-service
  cloud:
    stream:
      default:
        content-type: application/json;charset-UTF-8
        group: ${spring.application.name}
        consumer:
          partitioned: true
          headerMode: headers
        producer:
          headerMode: headers
      bindings:
        input:
          destination: topic-in
        output:
          destination: topic-out
          producer:
            partitionKeyExpression: payload.id1
  sleuth:
#    http:
#      legacy:
#        enabled: true
    integration:
      enabled: false
    messaging:
      kafka:
        enabled: true
#    traceId128: true
  main:
    banner-mode: 'off'
logging:
  level:
  zipkin2:
    reporter.xray_udp: trace
    storage.xray_udp: trace
